### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by haveaguess** [manjeshpv/node-express-passport-mysql#3]
Thanks for sharing this, it helped me get started with things. One thing I added was I use mysql escaping on the email otherwise you could suffer from a SQL injection attack right ?

**Comment by manjeshpv** [comment]
Can you please fork and add the code and Create a Pull request.

:)

**Comment by manjeshpv** [comment]
https://github.com/manjeshpv/node-express-passport-mysql/commit/11395a3303793afd846d8943e0e5652b4d17b197
