### ISSUE TITLE
Rethrow non-MySQL errors

### ISSUE THREAD

**Issue by bluegray1015** [manjeshpv/node-express-passport-mysql#8]
Hi, thank you for sharing this useful project.
When I launch this project, I encounter a mysql problem.
It's always happened when I try to login.

```
./node-express-passport-mysql-master/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^
Incorrect arguments
```

However, when I did signup, then I wouldn't have this problem. Everything works fine.
I tried to find solutions from the internet, but it didn't work.
Do you have any idea about this error?
I really appreciate your help.

**Comment by SerBad** [comment]
do you start your mysql server?

**Comment by rennan** [comment]
@bluegray1015 just start mysql server and configure locally the user and password, then, change the port number to 3003 (eg.) and run **node server.js** command.

**Comment by bluegray1015** [comment]
thank you.

**Comment by alavaia** [comment]
I just ran into this same issue. My code was failing on the bcrypt.compareSync() function in passport.js. The fix that worked for me was to change the password field in mysql to be CHAR(60) as I was originally using BINARY(60). The compareSync function from the bcrypt-nodejs module will throw an "Incorrect Arguments" error if either the password or the encrypted password in the database are not string types.  It will throw a "Not a valid BCrypt hash" error the field length is anything other than 60.

**Comment by sudhir600** [comment]
exactly the same i am facing. when i hit 3 or 4 time one by one 1st time its work good but then again i got error.
```
node_modules\mysql\lib\protocol\Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

when i kill the node process and started again its work but..only for 1st time. is there any solution? 

```
